### ISSUE TITLE
Enabling issue tracker for the Matterless elisp packages

### ISSUE THREAD

**Issue by Adocentyn** [msherry/Emacs-config#1]
Hello @msherry 
I'd like to report an issue I'm having while attempting to set the matterless packages, specifically the matterless-server.el one. Would it be possible to enable issue tracking on https://github.com/msherry/matterless-el ?

**Comment by msherry** [comment]
Hi there! This repo is my personal emacs config, and the repo you've linked to is a private fork of https://github.com/RobotDisco/matterless, so I'd reach out to them directly if you've having issues.
